[package]
name = "rpi-ledmatrix-rs"
version = "0.1.0"
authors = ["Nils Krüger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2.0"
